#!/usr/bin/env bash
# Script that runs dig command s against given args

subdomains=("www" "lb-01" "web-01" "web-02")

handler () {
	subdomain=$1
	domain=$2
	dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -1 | awk -v s="$subdomain" 'BEGIN { FS = " " } ; { print "The subdomain " s " is a " $4 " record and points to " $5 }'
}
if [ $# -eq 1 ]; then
	domain="$1"
	for subdomain in "${subdomains[@]}"
	do
		handler "$subdomain" "$domain"
	done
elif [ $# -eq 2 ]; then
	domain="$1"
	subdomain="$2"
	handler "$subdomain" "$domain"
fi
