#!/usr/bin/env bash
# Script to debug a web stack refusing port 80 connections

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
