#!/usr/bin/env bash
# Script to write a statement indefinitely
# Intercept a SIGTERM signal to display a message

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
