#!/usr/bin/env bash
# Run nginx as another user
chmod 644 /etc/nginx/nginx.conf
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
pkill -f apache2
sudo -u nginx service nginx restart
